server:
  port: 9090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 5
  serviceUrl:
      defaultZone: http://localhost:9090/eureka